### ISSUE TITLE
Formation-breaking Behavior

### ISSUE THREAD

**Issue by hydragyrum32** [kikotheexile/Endless-Sky-Civil-War#125] opened 2020-10-27 21:20 UTC
**Is your feature request related to a problem? Please describe.**
Ships in formations will break formation whenever a hostile ship is detected, without the player having any ability to decide under what conditions ships should break formation

**Related Issue Links**
Has anyone else had this issue or idea? Share some links to those [Issues](https://github.com/endless-sky/endless-sky/issues), [Google Group threads](https://groups.google.com/forum/#!categories/endless-sky), or [Steam forum posts](https://steamcommunity.com/app/404410/discussions/)

**Describe the solution you'd like**
A setting (in the settings panel) to choose from two or more behaviors for breaking formation. A simple on/off switch for whether or not to break formation would suffice, but more detailed options (never, when close, on aggro) would be preferable

**Describe alternatives you've considered**
A keybind to toggle current behavior could replace or augment the setting (like with ammo usage for escorts)
A more sophisticated automatic system to decide when to leave formation could also solve the issue

**Comment by petervdmeer** [comment] 2021-02-20 22:28
Isn't this already handled for players by having the Gather command? Ships that are ordered to gather will stay with the player until they are ordered to no longer gather. (And yes, I feel that ships that have the gather order should also go into formation. Not sure if that is already implemented somewhere.)

For AI-ships I would expect a new personality that handles this (protector-personality => always stay with the flagship).

**Comment by kikotheexile** [comment] 2021-02-20 22:56
If the personality already exists, I can throw that into all the text files. If it doesn't, well, i barely understand how MZ's simple AI work in the first place, so i would have to ask someone more experienced in code to add that personality, but then i would handle all the text file changes myself.

**Comment by kikotheexile** [comment] 2021-05-23 09:05
This is not a large enough issue for me to leave this open ended and without discussion. I will close this issue for now with the option to re-open it later when ship AI comes back into focus.

**Closed as completed by kikotheexile** 2021-05-23 09:05 UTC
Labels: enhancement

**Comment by petervdmeer** [comment] 2021-05-23 20:48
This request is not specific for formations, players (and story writers for NPCs) would also like to control when ships stay close to the flagship and when they break away from the main fleet in general.

Issue https://github.com/endless-sky/endless-sky/issues/802 in ES then seems similar to this issue, so I don't see a need to file a separate issue for ES either (the issue is already known/requested in 802).

**Comment by petervdmeer** [comment] 2021-05-23 20:52
Maybe nice to know that issues https://github.com/endless-sky/endless-sky/pull/5621 (keeping the fleet together during landing) and https://github.com/endless-sky/endless-sky/pull/5583 (let NPC flagship slowdown on slow escorts) were inspired by this request. (Both those PRs improve formation flying behavior by improving generic fleet behavior.)

**Comment by kikotheexile** [comment] 2021-05-23 20:56
We are unfortunately not up to date with base endless sky and i have no intention of being the person to bring us back up to date with them, as my focus is specifically on finishing human content. 

But that is great information to have.
